server:
  port: 8083

spring:
  application:
    name: bank-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none

driver-service:
  url: ${DRIVER_SERVICE_URI:http://localhost:8081/driver}

passenger-service:
  url: ${PASSENGER_SERVICE_URI:http://localhost:8080/passenger}

eureka:
  client:
    service-url:
      defaultZone: ${REGISTRY_SERVICE_URI:http://localhost:8761/eureka/}

resilience4j:
  circuitbreaker:
    instances:
      passenger-service:
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        automatic-transition-from-open-to-half-open-enabled: true
      driver-service:
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10s
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        automatic-transition-from-open-to-half-open-enabled: true

passenger-service:
  url: ${PASSENGER_SERVICE_URI:http://localhost:8080/passenger}