server:
  port: 8765

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passenger
          uri: lb://passenger-service
          predicates:
            - Path=/passenger/**

        - id: driver
          uri: lb://driver-service
          predicates:
            - Path=/driver/**

        - id: ride
          uri: lb://ride-service
          predicates:
            - Path=/ride/**

        - id: bank
          uri: lb://bank-service
          predicates:
            - Path=/bank/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${REGISTRY_SERVICE_URI:http://localhost:8761/eureka/}